"""HTML report rendering for completed Roadlytics jobs."""

from __future__ import annotations

from html import escape
from typing import Dict, List


def _summary_row(label: str, value: str) -> str:
    return (
        "<div class='metric'>"
        f"<span class='metric-label'>{escape(label)}</span>"
        f"<strong>{escape(value)}</strong>"
        "</div>"
    )


def render_report_html(
    job: Dict[str, object],
    analytics: Dict[str, object],
    artifacts: List[Dict[str, object]],
) -> str:
    isolated = analytics.get("isolated_components", 0)
    largest = analytics.get("largest_component_length_km", 0)
    critical = analytics.get("critical_junction_count", analytics.get("critical_junctions", 0))
    component_count = analytics.get("component_count", analytics.get("total_components", 0))

    downloads = "".join(
        (
            "<li>"
            f"<strong>{escape(str(artifact['label']))}</strong>"
            f"<span>{escape(str(artifact['filename']))}</span>"
            "</li>"
        )
        for artifact in artifacts
        if artifact.get("is_download")
    )

    metrics = "".join(
        [
            _summary_row("Status", str(job.get("status", ""))),
            _summary_row("Segmenter", str(job.get("segmenter", ""))),
            _summary_row("Classifier", str(job.get("classifier", ""))),
            _summary_row("Connected Components", str(component_count)),
            _summary_row("Isolated Components", str(isolated)),
            _summary_row("Largest Component (km)", f"{largest}"),
            _summary_row("Critical Junctions", str(critical)),
        ]
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Roadlytics Report - {escape(str(job.get("project_name", "Assessment")))}</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f8f2eb;
      --panel: #fffaf5;
      --border: #d8cab9;
      --text: #2c2418;
      --muted: #6d6356;
      --accent: #b8763e;
      --good: #228b22;
      --unpaved: #d6392a;
      --damaged: #f0c419;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      padding: 40px;
      background: linear-gradient(180deg, #fbf6f1 0%, #f1e7da 100%);
      color: var(--text);
      font-family: "Segoe UI", sans-serif;
    }}
    .wrap {{
      max-width: 980px;
      margin: 0 auto;
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 24px;
      overflow: hidden;
      box-shadow: 0 24px 80px rgba(64, 44, 25, 0.08);
    }}
    header {{
      padding: 36px 40px 24px;
      background: radial-gradient(circle at top right, rgba(184, 118, 62, 0.18), transparent 35%), #fff8f1;
      border-bottom: 1px solid var(--border);
    }}
    h1 {{
      margin: 0;
      font-size: 32px;
      line-height: 1.1;
    }}
    p {{
      color: var(--muted);
      line-height: 1.7;
    }}
    main {{
      padding: 32px 40px 40px;
      display: grid;
      gap: 28px;
    }}
    .metrics {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 14px;
    }}
    .metric {{
      padding: 18px;
      border-radius: 18px;
      background: white;
      border: 1px solid var(--border);
      display: grid;
      gap: 8px;
    }}
    .metric-label {{
      font-size: 12px;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }}
    .legend {{
      display: flex;
      gap: 14px;
      flex-wrap: wrap;
    }}
    .legend-item {{
      display: inline-flex;
      gap: 8px;
      align-items: center;
      color: var(--muted);
    }}
    .swatch {{
      width: 14px;
      height: 14px;
      border-radius: 999px;
      border: 1px solid rgba(0, 0, 0, 0.08);
    }}
    ul {{
      margin: 0;
      padding-left: 20px;
      color: var(--muted);
    }}
    li {{
      margin-bottom: 8px;
    }}
    .downloads li {{
      display: flex;
      justify-content: space-between;
      gap: 12px;
    }}
  </style>
</head>
<body>
  <div class="wrap">
    <header>
      <h1>{escape(str(job.get("project_name", "Roadlytics Assessment")))}</h1>
      <p>{escape(str(job.get("description", "")))}</p>
      <p>Generated by Roadlytics using {escape(str(job.get("segmenter", "")))} segmentation and {escape(str(job.get("classifier", "")))} classification.</p>
    </header>
    <main>
      <section>
        <h2>Operational Summary</h2>
        <div class="metrics">{metrics}</div>
      </section>
      <section>
        <h2>Condition Legend</h2>
        <div class="legend">
          <div class="legend-item"><span class="swatch" style="background: var(--good);"></span>Good</div>
          <div class="legend-item"><span class="swatch" style="background: var(--unpaved);"></span>Unpaved</div>
          <div class="legend-item"><span class="swatch" style="background: var(--damaged);"></span>Damaged</div>
        </div>
      </section>
      <section>
        <h2>Connectivity Notes</h2>
        <p>This report uses raster-derived connectivity from the segmentation mask and the combined road-condition raster. High betweenness cells are surfaced as critical junctions, and disconnected road groups are tracked as components.</p>
      </section>
      <section>
        <h2>Downloads</h2>
        <ul class="downloads">{downloads}</ul>
      </section>
    </main>
  </div>
</body>
</html>
"""
