# -*- coding: utf-8 -*-
"""road_condition_mask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9v0-LUBQZe6tzIyjSQZT2JczzDpnY8V
"""

# 1. Mount Google Drive (Run this cell first and accept permissions)
from google.colab import drive
drive.mount('/content/drive')

# 2. Install rasterio (Colab doesn't have it by default)
!pip install rasterio -q

import rasterio
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# --- CONFIGURATION ---
# Update these paths if your folder structure is slightly different
STACK_PATH = '/content/drive/MyDrive/FYP2/data/raw/sindh_stack.tif'
MASK_PATH = '/content/drive/MyDrive/FYP2/data/raw/road_mask.tif'
OUTPUT_PATH = '/content/drive/MyDrive/FYP2/data/raw/road_condition_mask.tif'

print("Loading data...")
# 3. Load the Data
with rasterio.open(STACK_PATH) as src_stack:
    # Read all 4 bands (Blue, Green, Red, NIR) and convert to float32
    stack = src_stack.read().astype(np.float32)
    meta = src_stack.meta

with rasterio.open(MASK_PATH) as src_mask:
    # Read the binary road mask (0 = Background, 1 = Road)
    mask = src_mask.read(1)

print("Calculating Spectral Indices...")
# 4. Calculate Spectral Indices
# Avoid division by zero by adding a tiny number (1e-8)
blue, green, red, nir = stack[0], stack[1], stack[2], stack[3]

ndvi = (nir - red) / (nir + red + 1e-8)
brightness = (blue + green + red) / 3.0

# 5. Extract ONLY the Road Pixels
# We don't want to cluster the sand and trees, only the roads
print("Extracting road features...")
road_y, road_x = np.where(mask == 1)

# Stack our features into a 2D array: (Number_of_Road_Pixels, 6_Features)
features = np.column_stack([
    blue[road_y, road_x],
    green[road_y, road_x],
    red[road_y, road_x],
    nir[road_y, road_x],
    ndvi[road_y, road_x],
    brightness[road_y, road_x]
])

# Normalize features (important for K-Means so brightness doesn't overpower NDVI)
from sklearn.preprocessing import StandardScaler
features_scaled = StandardScaler().fit_transform(features)

print(f"Running K-Means on {len(road_y)} road pixels. This might take a minute...")
# 6. Run K-Means Clustering (Aiming for 3 classes: Good, Damaged, Unpaved)
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
clusters = kmeans.fit_predict(features_scaled)

# 7. Map the clusters back to an image
# Create a blank image of zeros
condition_mask = np.zeros_like(mask, dtype=np.uint8)

# Assign cluster values (adding 1 so classes are 1, 2, 3 instead of 0, 1, 2)
condition_mask[road_y, road_x] = clusters + 1

print("Saving condition mask to Google Drive...")
# 8. Save the Output
meta.update(count=1, dtype='uint8', nodata=0)
with rasterio.open(OUTPUT_PATH, 'w', **meta) as dst:
    dst.write(condition_mask, 1)

print("Done! You can now download and view 'road_condition_mask.tif' in QGIS.")

# --- Optional: Quick Visualization ---
plt.figure(figsize=(10, 10))
plt.imshow(condition_mask, cmap='viridis')
plt.title("Road Condition Clusters")
plt.axis('off')
plt.show()

import pandas as pd
import seaborn as sns

print("Analyzing Cluster Characteristics...")

# 1. Create a DataFrame for easy plotting and analysis
# We will use the unscaled features (original values) so the numbers make sense to humans
df = pd.DataFrame({
    'Brightness': features[:, 5], # The 6th column we created
    'NDVI': features[:, 4],       # The 5th column
    'Cluster': clusters + 1       # +1 to match your 1, 2, 3 labels
})

# 2. Print the Averages (Centroids)
print("\n--- Average Values per Cluster ---")
summary = df.groupby('Cluster').mean()
print(summary)

print("\nGenerating Scatter Plot...")
# 3. Create a Scatter Plot (We sample 5,000 points so it doesn't crash your browser)
# If you have less than 5000 road pixels, it will just use all of them
sample_df = df.sample(n=min(5000, len(df)), random_state=42)

plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=sample_df,
    x='Brightness',
    y='NDVI',
    hue='Cluster',
    palette=['#1f77b4', '#ff7f0e', '#2ca02c'], # Blue, Orange, Green
    alpha=0.6,
    s=15
)

plt.title("Road Pixel Clusters: Brightness vs. NDVI")
plt.xlabel("Overall Brightness (Reflectance)")
plt.ylabel("NDVI (Vegetation/Damage Level)")
plt.legend(title="Cluster ID")
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

import rasterio
import numpy as np
import matplotlib.pyplot as plt

# --- 1. Load the Condition Mask ---
MASK_PATH = '/content/drive/MyDrive/FYP2/data/raw/road_condition_mask.tif'

with rasterio.open(MASK_PATH) as src:
    condition_mask = src.read(1)
    meta = src.meta

# --- 2. Map the Clusters to their meaning ---
# Based on your scatter plot averages:
# Cluster 2 (Orange) = Good (Highest Brightness, Lowest NDVI)
# Cluster 1 (Blue)   = Damaged (Moderate Brightness, Moderate NDVI)
# Cluster 3 (Green)  = Unpaved (Lowest Brightness, Highest NDVI)

print("Splitting clusters into separate files...")

# Create binary masks (1 for the target class, 0 for everything else)
# --- 2. THE NEW CORRECTED MAPPING ---
# Cluster 1 (Blue) = Good Paved Asphalt (Darker than sand)
good_mask = np.where(condition_mask == 1, 1, 0).astype(np.uint8)

# Cluster 2 (Orange) = Unpaved Dirt (Highly reflective sand)
unpaved_mask = np.where(condition_mask == 2, 1, 0).astype(np.uint8)

# Cluster 3 (Green) = Damaged / Tree-Covered (High vegetation signature)
damaged_mask = np.where(condition_mask == 3, 1, 0).astype(np.uint8)

# --- 3. Save the separate files ---
meta.update(dtype='uint8')

# Save Good Roads
with rasterio.open('/content/drive/MyDrive/FYP2/data/raw/verify_good.tif', 'w', **meta) as dst:
    dst.write(good_mask, 1)

# Save Damaged Roads
with rasterio.open('/content/drive/MyDrive/FYP2/data/raw/verify_damaged.tif', 'w', **meta) as dst:
    dst.write(damaged_mask, 1)

# Save Unpaved Roads
with rasterio.open('/content/drive/MyDrive/FYP2/data/raw/verify_unpaved.tif', 'w', **meta) as dst:
    dst.write(unpaved_mask, 1)

print("✅ Saved 3 separate GeoTIFFs to your drive!")

# --- 4. Quick Visual Preview in Colab ---
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
axes[0].imshow(good_mask, cmap='Oranges')
axes[0].set_title('Cluster 2: Good (Paved)')
axes[0].axis('off')

axes[1].imshow(damaged_mask, cmap='Blues')
axes[1].set_title('Cluster 1: Damaged')
axes[1].axis('off')

axes[2].imshow(unpaved_mask, cmap='Greens')
axes[2].set_title('Cluster 3: Unpaved (Dirt)')
axes[2].axis('off')

plt.tight_layout()
plt.show()

from google.colab import drive
drive.mount('/content/drive')
import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# Machine Learning & Metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Geospatial
import rasterio

# Deep Learning
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from torchvision import models
import albumentations as A

# Utilities (auto-detects Jupyter/Colab environment for nice progress bars)
from tqdm.auto import tqdm


# ==========================================
# CONFIGURATION
# ==========================================
DRIVE_ROOT     = Path('/content/drive/MyDrive/FYP2')
STACK_PATH     = DRIVE_ROOT / 'data' / 'raw' / 'sindh_stack.tif'
COND_MASK_PATH = DRIVE_ROOT / 'data' / 'raw' / 'road_condition_mask.tif'
# Use Colab's local storage for tiny files to speed up I/O significantly
PATCHES_DIR    = Path('/content/condition_patches')

NUM_CLASSES    = 3
PATCH_SIZE     = 32
STRIDE         = 16
REFLECTANCE_SCALE = 10000.0

# ==========================================
# PHASE 2: EXTRACT TRAINING PATCHES
# ==========================================
print("\n" + "="*50)
print("PHASE 2: EXTRACT TRAINING PATCHES")
print("="*50)

for cls in range(NUM_CLASSES):
    (PATCHES_DIR / f'class_{cls}' / 'images').mkdir(parents=True, exist_ok=True)

print("Loading Sentinel-2 stack...")
with rasterio.open(STACK_PATH) as src:
    image = np.clip(src.read().astype(np.float32), 0, 10000) / REFLECTANCE_SCALE

print("Loading K-Means condition mask...")
with rasterio.open(COND_MASK_PATH) as src:
    cond_mask = src.read(1).astype(np.int32)

pad = PATCH_SIZE // 2
image_padded = np.pad(image, ((0,0),(pad,pad),(pad,pad)), mode='reflect')

counts = {cls: 0 for cls in range(NUM_CLASSES)}

# K-Means clusters are stored as 1, 2, 3. Filter and apply stride.
road_pixels = np.argwhere((cond_mask >= 1) & (cond_mask <= NUM_CLASSES))[::STRIDE]

print("Extracting patches...")
for r, c in tqdm(road_pixels, desc='Extracting patches'):
    label = int(cond_mask[r, c])
    if label < 1 or label > NUM_CLASSES:
        continue

    cls_idx = label - 1   # convert 1-indexed K-Means label to 0-indexed class folder

    # Extract patch (shifted by pad since image was padded)
    patch = image_padded[:, r:r+PATCH_SIZE, c:c+PATCH_SIZE]
    if patch.shape != (4, PATCH_SIZE, PATCH_SIZE):
        continue

    fname = f'r{r:05d}_c{c:05d}.npy'
    np.save(PATCHES_DIR / f'class_{cls_idx}' / 'images' / fname, patch)
    counts[cls_idx] += 1

print("Extraction complete!")
for cls, cnt in counts.items():
    print(f"  Class {cls}: {cnt:,} patches")

# ==========================================
# PHASE 3: DATASET & DATALOADERS
# ==========================================
print("\n" + "="*50)
print("PHASE 3: DATASET & DATALOADERS")
print("="*50)

BATCH_SIZE = 256
NUM_WORKERS = 2 # Reduced slightly for Colab stability
RANDOM_SEED = 42

cond_transform = A.Compose([
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.5),
    A.RandomRotate90(p=0.5),
    A.RandomBrightnessContrast(brightness_limit=0.1, contrast_limit=0.1, p=0.3),
])

class ConditionPatchDataset(Dataset):
    def __init__(self, paths_and_labels, augment=False):
        self.items = paths_and_labels
        self.augment = augment

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        path, label = self.items[idx]
        patch = np.load(path)
        if self.augment:
            patch_hwc = patch.transpose(1, 2, 0)
            aug = cond_transform(image=patch_hwc)
            patch = aug['image'].transpose(2, 0, 1).astype(np.float32)
        return torch.from_numpy(patch.astype(np.float32)), torch.tensor(label, dtype=torch.long)

# Collect all paths and labels
all_items = []
for cls in range(NUM_CLASSES):
    cls_dir = PATCHES_DIR / f'class_{cls}' / 'images'
    for p in cls_dir.glob('*.npy'):
        all_items.append((str(p), cls))

random.Random(RANDOM_SEED).shuffle(all_items)
print(f"Total patches: {len(all_items)}")

# Split Dataset
train_items, test_items = train_test_split(all_items, test_size=0.2, random_state=RANDOM_SEED, stratify=[x[1] for x in all_items])
train_items, val_items = train_test_split(train_items, test_size=0.15, random_state=RANDOM_SEED, stratify=[x[1] for x in train_items])
print(f"Train: {len(train_items)} | Val: {len(val_items)} | Test: {len(test_items)}")

# Weighted sampler for class imbalance
class_counts = [sum(1 for _, lbl in train_items if lbl == c) for c in range(NUM_CLASSES)]
class_weights = [1.0 / max(cnt, 1) for cnt in class_counts]
sample_weights = [class_weights[lbl] for _, lbl in train_items]
sampler = WeightedRandomSampler(sample_weights, num_samples=len(sample_weights), replacement=True)

train_ds = ConditionPatchDataset(train_items, augment=True)
val_ds   = ConditionPatchDataset(val_items,   augment=False)
test_ds  = ConditionPatchDataset(test_items,  augment=False)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, sampler=sampler, num_workers=NUM_WORKERS, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False,   num_workers=NUM_WORKERS, pin_memory=True)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False,   num_workers=NUM_WORKERS, pin_memory=True)

# ==========================================
# PHASE 4: EFFICIENTNET-B2 TRAINING
# ==========================================
print("\n" + "="*50)
print("PHASE 4: EFFICIENTNET-B2 TRAINING")
print("="*50)

COND_LR = 1e-3
COND_EPOCHS = 50
COND_PATIENCE = 10
COND_CKPT_PATH = DRIVE_ROOT / 'outputs' / 'road_condition_model.pth'
COND_CKPT_PATH.parent.mkdir(parents=True, exist_ok=True)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Build EfficientNet-B2
backbone = models.efficientnet_b2(weights='IMAGENET1K_V1')

# Patch stem conv to 4 channels
old_conv = backbone.features[0][0]
new_conv = nn.Conv2d(4, old_conv.out_channels, kernel_size=old_conv.kernel_size,
                     stride=old_conv.stride, padding=old_conv.padding, bias=False)
with torch.no_grad():
    new_conv.weight[:, :3] = old_conv.weight
    new_conv.weight[:, 3]  = old_conv.weight.mean(dim=1)
backbone.features[0][0] = new_conv

# Replace head
in_features = backbone.classifier[1].in_features
backbone.classifier[1] = nn.Linear(in_features, NUM_CLASSES)

model_cond = backbone.to(device)
print(f"EfficientNet-B2 built. Parameters: {sum(p.numel() for p in model_cond.parameters()):,}")

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model_cond.parameters(), lr=COND_LR, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=COND_EPOCHS)

best_val_acc = 0.0
no_improve = 0

print(f"\nTraining on {device} for up to {COND_EPOCHS} epochs...")

for epoch in range(1, COND_EPOCHS + 1):
    # --- TRAIN ---
    model_cond.train()
    total_loss, correct, total = 0.0, 0, 0
    for patches, labels in tqdm(train_loader, desc=f'Epoch {epoch:02d} train', leave=False):
        patches, labels = patches.to(device), labels.to(device)
        optimizer.zero_grad()
        logits = model_cond(patches)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        correct += (logits.argmax(1) == labels).sum().item()
        total += labels.size(0)

    train_loss = total_loss / len(train_loader)
    train_acc = correct / total

    # --- VALIDATE ---
    model_cond.eval()
    v_loss, v_correct, v_total = 0.0, 0, 0
    with torch.no_grad():
        for patches, labels in val_loader:
            patches, labels = patches.to(device), labels.to(device)
            logits = model_cond(patches)
            v_loss += criterion(logits, labels).item()
            v_correct += (logits.argmax(1) == labels).sum().item()
            v_total += labels.size(0)

    val_loss = v_loss / len(val_loader)
    val_acc = v_correct / v_total

    scheduler.step()

    print(f"Epoch {epoch:02d}/{COND_EPOCHS} | Train Loss: {train_loss:.4f} Acc: {train_acc:.4f} | Val Loss: {val_loss:.4f} Acc: {val_acc:.4f}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model_cond.state_dict(), COND_CKPT_PATH)
        print(f"  ✓ New best val acc: {best_val_acc:.4f} — saved!")
        no_improve = 0
    else:
        no_improve += 1
        if no_improve >= COND_PATIENCE:
            print(f"\nEarly stopping at epoch {epoch}.")
            break

# ==========================================
# PHASE 5: TEST EVALUATION
# ==========================================
print("\n" + "="*50)
print("PHASE 5: TEST SET EVALUATION")
print("="*50)

model_cond.load_state_dict(torch.load(COND_CKPT_PATH, map_location=device))
model_cond.eval()

all_preds, all_labels = [], []
with torch.no_grad():
    for patches, labels in tqdm(test_loader, desc='Test eval'):
        patches = patches.to(device)
        preds = model_cond(patches).argmax(1).cpu().numpy()
        all_preds.extend(preds)
        all_labels.extend(labels.numpy())

label_names = ['Good (Cluster 1)', 'Unpaved (Cluster 2)', 'Damaged (Cluster 3)']
print("\nClassification Report:")
print(classification_report(all_labels, all_preds, target_names=label_names))

print("Generating Confusion Matrix...")
cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=label_names, yticklabels=label_names)
plt.title('Road Condition Classifier — Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.tight_layout()
plt.show()

print("\nPipeline Complete! 🎉")

import os
from pathlib import Path
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning & Metrics
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Geospatial
import rasterio

# Deep Learning
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from torchvision import models
import albumentations as A
from tqdm.auto import tqdm
# ==========================================
# PHASE 1: K-MEANS ROAD CONDITION CLUSTERING
# ==========================================


print("\n" + "="*50)
print("PHASE 1: K-MEANS ROAD CONDITION CLUSTERING")
print("="*50)

# --- CONFIGURATION ---
DRIVE_ROOT = Path('/content/drive/MyDrive/FYP2')
STACK_PATH = DRIVE_ROOT / 'data' / 'raw' / 'sindh_stack2.tif'
MASK_PATH = DRIVE_ROOT / 'data' / 'raw' / 'road_mask2.tif'
OUTPUT_PATH = DRIVE_ROOT / 'data' / 'raw' / 'road_condition_mask2.tif'

print("Loading data for clustering...")
# Load the Data
with rasterio.open(STACK_PATH) as src_stack:
    # Read all 4 bands (Blue, Green, Red, NIR) and convert to float32
    stack = src_stack.read().astype(np.float32)
    meta = src_stack.meta

with rasterio.open(MASK_PATH) as src_mask:
    # Read the binary road mask (0 = Background, 1 = Road)
    mask = src_mask.read(1)

print("Calculating Spectral Indices...")
# Avoid division by zero by adding a tiny number (1e-8)
blue, green, red, nir = stack[0], stack[1], stack[2], stack[3]

ndvi = (nir - red) / (nir + red + 1e-8)
brightness = (blue + green + red) / 3.0

print("Extracting road features...")
road_y, road_x = np.where(mask == 1)

# Stack our features into a 2D array: (Number_of_Road_Pixels, 6_Features)
features = np.column_stack([
    blue[road_y, road_x],
    green[road_y, road_x],
    red[road_y, road_x],
    nir[road_y, road_x],
    ndvi[road_y, road_x],
    brightness[road_y, road_x]
])

# Normalize features (important for K-Means so brightness doesn't overpower NDVI)
features_scaled = StandardScaler().fit_transform(features)

print(f"Running K-Means on {len(road_y)} road pixels. This might take a minute...")
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
clusters = kmeans.fit_predict(features_scaled)

# Map the clusters back to an image
condition_mask = np.zeros_like(mask, dtype=np.uint8)
condition_mask[road_y, road_x] = clusters + 1 # 1, 2, 3 instead of 0, 1, 2

print("Saving combined condition mask...")
meta.update(count=1, dtype='uint8', nodata=0)
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
with rasterio.open(OUTPUT_PATH, 'w', **meta) as dst:
    dst.write(condition_mask, 1)

# --- THE NEW CORRECTED MAPPING ---
# Cluster 1 (Blue) = Good Paved Asphalt (Darker than sand)
# Cluster 2 (Orange) = Unpaved Dirt (Highly reflective sand)
# Cluster 3 (Green) = Damaged / Tree-Covered (High vegetation signature)
good_mask = np.where(condition_mask == 1, 1, 0).astype(np.uint8)
unpaved_mask = np.where(condition_mask == 2, 1, 0).astype(np.uint8)
damaged_mask = np.where(condition_mask == 3, 1, 0).astype(np.uint8)

meta.update(dtype='uint8')
with rasterio.open(DRIVE_ROOT / 'data/raw/verify_good2.tif', 'w', **meta) as dst:
    dst.write(good_mask, 1)
with rasterio.open(DRIVE_ROOT / 'data/raw/verify_damaged2.tif', 'w', **meta) as dst:
    dst.write(damaged_mask, 1)
with rasterio.open(DRIVE_ROOT / 'data/raw/verify_unpaved2.tif', 'w', **meta) as dst:
    dst.write(unpaved_mask, 1)

print("✅ Saved 3 separate GeoTIFFs to your drive!")

import os
import torch
import torch.nn as nn
import rasterio
import numpy as np
from pathlib import Path
from torchvision import models
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm

# ==========================================
# CONFIGURATION
# ==========================================
DRIVE_ROOT      = Path('/content/drive/MyDrive/FYP2')

# Inputs (Your new unseen data)
STACK2_PATH     = DRIVE_ROOT / 'data' / 'raw' / 'sindh_stack2.tif'
ROAD_MASK2_PATH = DRIVE_ROOT / 'data' / 'raw' / 'road_mask2.tif'

# K-Means Ground Truth for the new image (for accuracy comparison)
# Assuming you ran Phase 1 on the new image to generate this
KMEANS_MASK2_PATH = DRIVE_ROOT / 'data' / 'raw' / 'road_condition_mask2.tif'

# Your trained model weights
MODEL_CKPT_PATH = DRIVE_ROOT / 'outputs' / 'road_condition_model.pth'

# Outputs
OUTPUT_PRED_TIF = DRIVE_ROOT / 'outputs' / 'dl_predictions2.tif'

PATCH_SIZE      = 32
NUM_CLASSES     = 3
REFLECTANCE_SCALE = 10000.0
BATCH_SIZE      = 256
NUM_WORKERS     = 2
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# ==========================================
# 1. LOAD MODEL
# ==========================================
print("Loading EfficientNet-B2 Model...")
backbone = models.efficientnet_b2(weights=None) # No need to download ImageNet weights for inference

# Rebuild the 4-channel structure
old_conv = backbone.features[0][0]
new_conv = nn.Conv2d(4, old_conv.out_channels, kernel_size=old_conv.kernel_size,
                     stride=old_conv.stride, padding=old_conv.padding, bias=False)
backbone.features[0][0] = new_conv

in_features = backbone.classifier[1].in_features
backbone.classifier[1] = nn.Linear(in_features, NUM_CLASSES)

model = backbone.to(device)
model.load_state_dict(torch.load(MODEL_CKPT_PATH, map_location=device))
model.eval()

# ==========================================
# 2. LOAD SATELLITE DATA
# ==========================================
print(f"\nLoading new satellite image: {STACK2_PATH.name}")
with rasterio.open(STACK2_PATH) as src:
    image = np.clip(src.read().astype(np.float32), 0, 10000) / REFLECTANCE_SCALE
    meta = src.meta

print(f"Loading road mask: {ROAD_MASK2_PATH.name}")
with rasterio.open(ROAD_MASK2_PATH) as src:
    road_mask = src.read(1)

pad = PATCH_SIZE // 2
image_padded = np.pad(image, ((0,0),(pad,pad),(pad,pad)), mode='reflect')

# Find all pixels where the road exists
road_pixels = np.argwhere(road_mask == 1)
print(f"Found {len(road_pixels):,} road pixels to predict. This may take a few minutes...")

# ==========================================
# 3. INFERENCE DATASET & DATALOADER
# ==========================================
class InferenceDataset(Dataset):
    def __init__(self, padded_image, pixels, patch_size):
        self.image = padded_image
        self.pixels = pixels
        self.patch_size = patch_size

    def __len__(self):
        return len(self.pixels)

    def __getitem__(self, idx):
        r, c = self.pixels[idx]
        # Extract patch (r and c are automatically offset correctly in the padded image)
        patch = self.image[:, r:r+self.patch_size, c:c+self.patch_size]
        return torch.from_numpy(patch.astype(np.float32)), r, c

infer_ds = InferenceDataset(image_padded, road_pixels, PATCH_SIZE)
infer_loader = DataLoader(infer_ds, batch_size=BATCH_SIZE, num_workers=NUM_WORKERS, pin_memory=True)

# ==========================================
# 4. RUN PREDICTIONS
# ==========================================
print("\nRunning Deep Learning Predictions...")
# Create a blank array to hold our predictions
prediction_map = np.zeros_like(road_mask, dtype=np.uint8)

with torch.no_grad():
    for patches, rows, cols in tqdm(infer_loader, desc='Predicting'):
        patches = patches.to(device)
        # Get predictions
        logits = model(patches)
        preds = logits.argmax(1).cpu().numpy()

        # We add 1 because our K-Means classes were saved as 1, 2, 3 (not 0, 1, 2)
        preds_for_map = preds + 1

        # Place predictions back into their exact map coordinates
        prediction_map[rows.numpy(), cols.numpy()] = preds_for_map

# ==========================================
# 5. SAVE PREDICTION TIFF
# ==========================================
print(f"\nSaving prediction map to: {OUTPUT_PRED_TIF.name}")
meta.update(count=1, dtype='uint8', nodata=0)
OUTPUT_PRED_TIF.parent.mkdir(parents=True, exist_ok=True)
with rasterio.open(OUTPUT_PRED_TIF, 'w', **meta) as dst:
    dst.write(prediction_map, 1)

# ==========================================
# 6. EVALUATE AGAINST K-MEANS GROUND TRUTH
# ==========================================
if KMEANS_MASK2_PATH.exists():
    print(f"\nComparing Model Predictions against K-Means ({KMEANS_MASK2_PATH.name})...")
    with rasterio.open(KMEANS_MASK2_PATH) as src:
        kmeans_mask = src.read(1)

    # We only want to evaluate where the road actually is
    valid_mask = (road_mask == 1) & (kmeans_mask >= 1) & (kmeans_mask <= 3)

    true_labels = kmeans_mask[valid_mask]
    pred_labels = prediction_map[valid_mask]

    label_names = ['Good (Cluster 1)', 'Unpaved (Cluster 2)', 'Damaged (Cluster 3)']

    print("\nClassification Report (Deep Learning vs K-Means):")
    print(classification_report(true_labels, pred_labels, target_names=label_names))

    cm = confusion_matrix(true_labels, pred_labels)
    plt.figure(figsize=(7, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=label_names, yticklabels=label_names)
    plt.title('DL Model vs K-Means Ground Truth — Image 2')
    plt.xlabel('Deep Learning Prediction')
    plt.ylabel('K-Means Ground Truth')
    plt.tight_layout()
    plt.show()
else:
    print(f"\nCould not find K-Means mask at {KMEANS_MASK2_PATH}.")
    print("If you want to run the accuracy comparison, make sure you run Phase 1 on your new stack first to generate 'road_condition_mask2.tif'.")

print("\nInference Pipeline Complete! 🎉")