# -*- coding: utf-8 -*-
"""stage3_deeplabv3_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LljRotOKMW4ft-BZ__VM4uRqXVSFKdsY

# Stage 3 — U-Net Road Segmentation
**Project:** Deep Learning-Based Road Detection and Condition Assessment in Rural Sindh, Pakistan

**Before running:**
1. Go to `Runtime → Change runtime type → T4 GPU` and save.
2. Upload `sindh_stack.tif`, `road_mask.tif` (and optionally `cloud_mask.tif`) to your Google Drive at:
   `My Drive/FYP/data/raw/`
3. Run all cells top to bottom.

**Expected Drive structure after full run:**
```
My Drive/FYP/
├── data/
│   ├── raw/             ← you put your .tif files here
│   └── tiles/           ← generated automatically
│       ├── images/
│       └── masks/
└── outputs/
    ├── checkpoints/     ← best_model.pth saved here
    ├── training_metrics.json
    ├── training_curves.png
    └── segmentation_mask_predicted.tif
```

## Cell 1 — Mount Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

import os
# Verify the mount worked
print(os.listdir('/content/drive/MyDrive'))

"""## Cell 2 — Install Dependencies
This takes ~3 minutes on first run. After that, Colab caches most packages for the session.
"""

# GDAL must be installed via apt before the Python binding
!apt-get install -y gdal-bin libgdal-dev python3-gdal 2>/dev/null | tail -5

!pip install -q \
    rasterio \
    segmentation-models-pytorch==0.3.3 \
    albumentations \
    geopandas \
    shapely \
    tqdm

print("\nAll packages installed.")

"""## Cell 3 — Check GPU"""

import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}")

if device.type == 'cuda':
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    print("WARNING: No GPU found. Go to Runtime → Change runtime type → T4 GPU")

"""## Cell 4 — Configuration
All hyperparameters and paths in one place. **Only edit this cell** if you need to change settings.
"""

from pathlib import Path

# ── PATHS ──────────────────────────────────────────────────────────────────
DRIVE_ROOT   = Path('/content/drive/MyDrive/FYP')
RAW_DIR      = DRIVE_ROOT / 'data' / 'raw'
TILES_DIR    = DRIVE_ROOT / 'data' / 'tiles'
OUTPUT_DIR   = DRIVE_ROOT / 'outputs'
CKPT_DIR     = OUTPUT_DIR / 'checkpoints'

STACK_PATH      = RAW_DIR / 'sindh_stack.tif'
MASK_PATH       = RAW_DIR / 'road_mask.tif'
CLOUD_MASK_PATH = RAW_DIR / 'cloud_mask.tif'   # optional — leave as-is if you don't have it

PRED_MASK_PATH = OUTPUT_DIR / 'segmentation_mask_predicted.tif'
PRED_SHP_PATH  = OUTPUT_DIR / 'predicted_roads.shp'

# Create all directories
for d in [TILES_DIR/'images', TILES_DIR/'masks', CKPT_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# ── TILING ─────────────────────────────────────────────────────────────────
TILE_SIZE       = 1024    # Massive 10km x 10km view for the DeepLab architecture
STRIDE          = 512     # 50% overlap guarantees smooth continuity
MIN_ROAD_RATIO  = 0.005   # Rejects empty desert/farmland patches

# ── NORMALISATION ──────────────────────────────────────────────────────────
REFLECTANCE_SCALE = 10000.0   # Sentinel-2 raw values 0–10000 → divide → [0, 1]

# ── MODEL ──────────────────────────────────────────────────────────────────
ENCODER_NAME    = 'se_resnext101_32x4d'  # Squeeze-&-Excitation 101-layer heavy feature extractor
ENCODER_WEIGHTS = 'imagenet'
IN_CHANNELS     = 4    # B02 Blue, B03 Green, B04 Red, B08 NIR
NUM_CLASSES     = 1    # binary segmentation

# ── LOSS ───────────────────────────────────────────────────────────────────
BCE_WEIGHT  = 0.5
DICE_WEIGHT = 0.5

# ── TRAINING ───────────────────────────────────────────────────────────────
BATCH_SIZE          = 8          # Warning: Pulls ~70-80GB VRAM! Perfect for 95GB G4 instance.
NUM_EPOCHS          = 225
LEARNING_RATE       = 2e-4
WEIGHT_DECAY        = 1e-5
VAL_SPLIT           = 0.15
TEST_SPLIT          = 0.15
RANDOM_SEED         = 42
NUM_WORKERS         = 6     # Colab has 2 CPU cores — don't set higher
EARLY_STOP_PATIENCE = 10
LR_SCHED_PATIENCE   = 5

# ── INFERENCE ──────────────────────────────────────────────────────────────
THRESHOLD = 0.3

print("Config ready.")
print(f"Stack file exists: {STACK_PATH.exists()}")
print(f"Mask file exists:  {MASK_PATH.exists()}")
print(f"Cloud mask exists: {CLOUD_MASK_PATH.exists()} (optional)")

"""## Cell 5 — Utility Functions"""

import numpy as np
import random

def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True

def normalise(arr: np.ndarray, scale: float = REFLECTANCE_SCALE) -> np.ndarray:
    """Convert raw Sentinel-2 integers to float32 in [0, 1]."""
    return arr.astype(np.float32) / scale

set_seed(RANDOM_SEED)
print("Utilities ready.")

"""## Cell 6 — Tile Generator
Slices `sindh_stack.tif` and `road_mask.tif` into 256×256 `.npy` patches saved to Google Drive.

**Runtime:** ~10–20 minutes for a 10,000×10,000 image with stride=128.
**Skip this cell** if you already ran it and the tiles folder is populated.
"""

import rasterio
from tqdm.notebook import tqdm

def generate_tiles():
    # Check if tiles already exist
    existing = list((TILES_DIR / 'images').glob('*.npy'))
    if existing:
        print(f"Found {len(existing)} existing tiles. Delete {TILES_DIR} to regenerate.")
        return len(existing)

    print("Opening GeoTIFFs...")
    with rasterio.open(STACK_PATH) as src:
        image = np.clip(src.read().astype(np.float32), 0, 10000) / REFLECTANCE_SCALE # (4, H, W)
        H, W = src.height, src.width

    with rasterio.open(MASK_PATH) as src:
        mask = src.read(1).astype(np.float32)   # (H, W)

    # Load cloud mask if it exists
    cloud = None
    if CLOUD_MASK_PATH.exists():
        with rasterio.open(CLOUD_MASK_PATH) as src:
            cloud = src.read(1).astype(np.uint8)  # (H, W), 1 = cloudy
        print(f"Cloud mask loaded. Cloudy pixels: {cloud.sum():,}")

    print(f"Image shape: {image.shape}  |  Mask shape: {mask.shape}")

    rows = range(0, H - TILE_SIZE + 1, STRIDE)
    cols = range(0, W - TILE_SIZE + 1, STRIDE)
    total_positions = len(rows) * len(cols)

    saved = 0
    skipped_cloud = 0
    skipped_empty = 0

    with tqdm(total=total_positions, desc='Generating tiles') as pbar:
        for r in rows:
            for c in cols:
                img_patch  = image[:, r:r+TILE_SIZE, c:c+TILE_SIZE]   # (4, 256, 256)
                mask_patch = mask[r:r+TILE_SIZE, c:c+TILE_SIZE]        # (256, 256)

                # Skip cloudy patches
                if cloud is not None:
                    cloud_patch = cloud[r:r+TILE_SIZE, c:c+TILE_SIZE]
                    if cloud_patch.any():
                        skipped_cloud += 1
                        pbar.update(1)
                        continue

                # Skip patches with almost no road
                road_ratio = mask_patch.sum() / (TILE_SIZE * TILE_SIZE)
                if road_ratio < MIN_ROAD_RATIO:
                    skipped_empty += 1
                    pbar.update(1)
                    continue

                fname = f'patch_{r:05d}_{c:05d}.npy'
                np.save(TILES_DIR / 'images' / fname, img_patch)
                np.save(TILES_DIR / 'masks'  / fname, mask_patch[np.newaxis])  # (1,256,256)
                saved += 1
                pbar.update(1)

    print(f"\nDone. Saved: {saved} | Skipped (cloud): {skipped_cloud} | Skipped (empty): {skipped_empty}")
    return saved

n_tiles = generate_tiles()
print(f"Total usable tiles: {n_tiles}")

"""## Cell 7 — Dataset & DataLoaders"""

import torch
from torch.utils.data import Dataset, DataLoader
import albumentations as A
from sklearn.model_selection import train_test_split
import numpy as np

# ── Augmentation pipeline (training only) ──────────────────────────────────
train_transform = A.Compose([
    # We stripped out GaussNoise and ShiftScaleRotate so they stop destroying your rare roads
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.5),
    A.RandomRotate90(p=0.5),
    A.RandomBrightnessContrast(brightness_limit=0.15, contrast_limit=0.15, p=0.4),
])

class RoadTileDataset(Dataset):
    def __init__(self, image_paths, mask_paths, augment=False):
        assert len(image_paths) == len(mask_paths)
        self.image_paths = image_paths
        self.mask_paths  = mask_paths
        self.augment     = augment

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image = np.load(self.image_paths[idx])   # (4, TILE_SIZE, TILE_SIZE) float32
        mask  = np.load(self.mask_paths[idx])    # (1, TILE_SIZE, TILE_SIZE) float32

        # ── Topology Trick: Label Dilation ──
        # Ground truth roads are often just 1 pixel wide. This makes the model 'hesitate'
        # and create dotted lines. Dilating to 3px wide forces it to learn a continuous band.
        import cv2
        mask_hw = mask[0]
        mask_hw = cv2.dilate(mask_hw, np.ones((3, 3), np.uint8), iterations=1)

        if self.augment:
            # Albumentations expects HWC format
            image_hwc = image.transpose(1, 2, 0)
            aug = train_transform(image=image_hwc, mask=mask_hw)
            image = aug['image'].transpose(2, 0, 1).astype(np.float32)
            mask_hw  = aug['mask']

        mask = mask_hw[np.newaxis].astype(np.float32)
        return torch.from_numpy(image), torch.from_numpy(mask)


def get_dataloaders():
    img_paths = list((TILES_DIR / 'images').glob('*.npy'))
    mask_paths = list((TILES_DIR / 'masks').glob('*.npy'))

    img_names = set(p.name for p in img_paths)
    mask_names = set(p.name for p in mask_paths)
    common = sorted(list(img_names & mask_names))

    assert len(common) > 0, f"No paired tiles found in {TILES_DIR}. Run Cell 6 first."
    if len(img_paths) != len(mask_paths):
        print(f"Warning: Found {len(img_paths)} images and {len(mask_paths)} masks. Using {len(common)} intersecting.")

    all_img_paths  = [str(TILES_DIR / 'images' / n) for n in common]
    all_mask_paths = [str(TILES_DIR / 'masks' / n) for n in common]

    img_tv, img_test, mask_tv, mask_test = train_test_split(
        all_img_paths, all_mask_paths,
        test_size=TEST_SPLIT, random_state=RANDOM_SEED
    )
    img_train, img_val, mask_train, mask_val = train_test_split(
        img_tv, mask_tv,
        test_size=VAL_SPLIT / (1 - TEST_SPLIT), random_state=RANDOM_SEED
    )

    print(f"Train: {len(img_train)} | Val: {len(img_val)} | Test: {len(img_test)}")

    np.save(OUTPUT_DIR / 'test_img_paths.npy',  np.array(img_test))
    np.save(OUTPUT_DIR / 'test_mask_paths.npy', np.array(mask_test))

    train_ds = RoadTileDataset(img_train, mask_train, augment=True)
    val_ds   = RoadTileDataset(img_val,   mask_val,   augment=False)
    test_ds  = RoadTileDataset(img_test,  mask_test,  augment=False)

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,
                              num_workers=NUM_WORKERS, pin_memory=True)
    val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False,
                              num_workers=NUM_WORKERS, pin_memory=True)
    test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False,
                              num_workers=NUM_WORKERS, pin_memory=True)

    return train_loader, val_loader, test_loader

train_loader, val_loader, test_loader = get_dataloaders()
print("DataLoaders ready.")

"""## Cell 8 — Model"""

import segmentation_models_pytorch as smp
import ssl

# Bypass SSL verification for downloading pre-trained weights from expired certificates
ssl._create_default_https_context = ssl._create_unverified_context

def build_model():
    """
    DeepLabV3+ with SE-ResNeXt-101 encoder.
    DeepLabV3+ uses Atrous Spatial Pyramid Pooling (ASPP) to capture
    multi-scale context, which is dramatically better for road networks
    than a standard U-Net.
    """
    model = smp.DeepLabV3Plus(
        encoder_name    = ENCODER_NAME,      # 'se_resnext101_32x4d'
        encoder_weights = ENCODER_WEIGHTS,   # 'imagenet'
        in_channels     = IN_CHANNELS,       # 4
        classes         = NUM_CLASSES,       # 1
        activation      = None,
    )
    return model

model = build_model().to(device)

# Quick sanity check — must run in eval() mode!
model.eval()
with torch.no_grad():
    dummy = torch.randn(1, 4, TILE_SIZE, TILE_SIZE).to(device)
    out   = model(dummy)
    print(f"Model output shape: {out.shape}")
    del dummy, out
torch.cuda.empty_cache()
model.train()   # put back into training mode before the training loop

"""## Cell 9 — Loss Function & IoU Metric"""

import torch
import torch.nn.functional as F
import segmentation_models_pytorch as smp

# ── Loss Functions ──────────────────────────────────────────────────────────
# Focal Loss: down-weights easy background pixels, forces focus on hard road pixels
# Dice Loss:  directly optimises pixel overlap — ideal for class-imbalanced masks
# Combined:   60% Dice + 40% Focal gives strong road detection signal

focal_loss_fn = smp.losses.FocalLoss(mode='binary', alpha=0.25, gamma=2.0)
dice_loss_fn  = smp.losses.DiceLoss(mode='binary')

def combined_loss(logits, targets):
    """
    logits:  raw model output  (B, 1, H, W)
    targets: ground truth mask (B, 1, H, W)  values {0.0, 1.0}
    Returns: scalar loss
    """
    focal = focal_loss_fn(logits, targets)
    dice  = dice_loss_fn(logits, targets)
    return 0.4 * focal + 0.6 * dice


def iou_score(logits, targets, threshold=THRESHOLD):
    """
    Returns scalar IoU for a batch.
    Target metric: 65–75% on held-out test set (NFR-11).
    """
    pred   = (torch.sigmoid(logits) > threshold).float()
    smooth = 1e-6
    intersection = (pred * targets).sum()
    union        = pred.sum() + targets.sum() - intersection
    return ((intersection + smooth) / (union + smooth)).item()


print("Loss function and IoU metric defined.")

"""## Cell 10 — Training Loop
Trains for up to 50 epochs with early stopping (patience = 10).
Best checkpoint is saved to Google Drive automatically.

**Estimated time on T4 GPU:** ~2–4 minutes per epoch depending on number of tiles.
"""

import json
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm

set_seed(RANDOM_SEED)

optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='max', patience=LR_SCHED_PATIENCE, factor=0.5
)

best_val_iou           = 0.0
epochs_without_improve = 0
history = {'train_loss': [], 'val_loss': [], 'train_iou': [], 'val_iou': []}

print(f"Starting training on {device}. Saving best model to {CKPT_DIR / 'best_model.pth'}")
print("-" * 70)

for epoch in range(1, NUM_EPOCHS + 1):

    # ── TRAIN ──────────────────────────────────────────────────────────────
    model.train()
    train_loss_sum = 0.0
    train_iou_sum  = 0.0

    for images, masks in tqdm(train_loader, desc=f'Epoch {epoch:02d} train', leave=False):
        images, masks = images.to(device), masks.to(device)
        optimizer.zero_grad()
        logits = model(images)
        loss   = combined_loss(logits, masks)
        loss.backward()
        optimizer.step()
        train_loss_sum += loss.item()
        train_iou_sum  += iou_score(logits, masks)

    train_loss = train_loss_sum / len(train_loader)
    train_iou  = train_iou_sum  / len(train_loader)

    # ── VALIDATE ───────────────────────────────────────────────────────────
    model.eval()
    val_loss_sum = 0.0
    val_iou_sum  = 0.0

    with torch.no_grad():
        for images, masks in tqdm(val_loader, desc=f'Epoch {epoch:02d} val  ', leave=False):
            images, masks = images.to(device), masks.to(device)
            logits = model(images)
            val_loss_sum += combined_loss(logits, masks).item()
            val_iou_sum  += iou_score(logits, masks)

    val_loss = val_loss_sum / len(val_loader)
    val_iou  = val_iou_sum  / len(val_loader)

    # ── SCHEDULER ──────────────────────────────────────────────────────────
    scheduler.step(val_iou)
    current_lr = optimizer.param_groups[0]['lr']

    # ── LOGGING ────────────────────────────────────────────────────────────
    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['train_iou'].append(train_iou)
    history['val_iou'].append(val_iou)

    print(f"Epoch {epoch:02d}/{NUM_EPOCHS}  "
          f"train_loss={train_loss:.4f}  train_iou={train_iou:.4f}  "
          f"val_loss={val_loss:.4f}  val_iou={val_iou:.4f}  lr={current_lr:.2e}")

    # ── CHECKPOINT ─────────────────────────────────────────────────────────
    if val_iou > best_val_iou:
        best_val_iou = val_iou
        torch.save(model.state_dict(), CKPT_DIR / 'best_model.pth')
        print(f"  ✓ New best val IoU: {best_val_iou:.4f} — checkpoint saved.")
        epochs_without_improve = 0
    else:
        epochs_without_improve += 1
        if epochs_without_improve >= EARLY_STOP_PATIENCE:
            print(f"\nEarly stopping at epoch {epoch} (no improvement for {EARLY_STOP_PATIENCE} epochs).")
            break

print(f"\nTraining complete. Best val IoU: {best_val_iou:.4f}")

# ── TEST EVALUATION ────────────────────────────────────────────────────────
print("\nEvaluating on held-out test set...")
model.load_state_dict(torch.load(CKPT_DIR / 'best_model.pth'))
model.eval()

test_loss_sum = 0.0
test_iou_sum  = 0.0
with torch.no_grad():
    for images, masks in tqdm(test_loader, desc='Test eval'):
        images, masks = images.to(device), masks.to(device)
        logits = model(images)
        test_loss_sum += combined_loss(logits, masks).item()
        test_iou_sum  += iou_score(logits, masks)

test_loss = test_loss_sum / len(test_loader)
test_iou  = test_iou_sum  / len(test_loader)
print(f"Test loss: {test_loss:.4f}  |  Test IoU: {test_iou:.4f}")
print(f"NFR-11 target: 65–75% IoU  →  {'PASSED ✓' if 0.65 <= test_iou <= 0.75 else 'Check result'}")

# ── SAVE METRICS ───────────────────────────────────────────────────────────
metrics = {
    'best_val_iou': round(best_val_iou, 4),
    'test_iou': round(test_iou, 4),
    'test_loss': round(test_loss, 4),
    'epochs_trained': len(history['train_loss']),
    'model_checkpoint': str(CKPT_DIR / 'best_model.pth')
}
with open(OUTPUT_DIR / 'training_metrics.json', 'w') as f:
    json.dump(metrics, f, indent=2)
print(f"Metrics saved to {OUTPUT_DIR / 'training_metrics.json'}")

# ── PLOT CURVES ────────────────────────────────────────────────────────────
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

ax1.plot(history['train_loss'], label='Train Loss')
ax1.plot(history['val_loss'],   label='Val Loss')
ax1.set_title('Loss Curves'); ax1.set_xlabel('Epoch'); ax1.legend(); ax1.grid(True)

ax2.plot(history['train_iou'], label='Train IoU')
ax2.plot(history['val_iou'],   label='Val IoU')
ax2.axhline(0.65, color='green', linestyle='--', alpha=0.7, label='NFR-11 lower bound')
ax2.axhline(0.75, color='green', linestyle='--', alpha=0.7, label='NFR-11 upper bound')
ax2.set_title('IoU Curves'); ax2.set_xlabel('Epoch'); ax2.legend(); ax2.grid(True)

plt.tight_layout()
plt.savefig(OUTPUT_DIR / 'training_curves.png', dpi=150)
plt.show()
print(f"Curves saved to {OUTPUT_DIR / 'training_curves.png'}")

"""## Cell 11 — Full-Scene Inference
Loads `best_model.pth` and runs inference tile-by-tile over the entire `sindh_stack.tif`.
Stitches predictions back into a georeferenced GeoTIFF, preserving the original CRS and geotransform.

**This output (`segmentation_mask_predicted.tif`) is the direct input to Stage 4.**

**Runtime:** ~15–30 minutes for a 10,000×10,000 image.
"""

import rasterio
from tqdm.notebook import tqdm

def run_inference():
    # Load best model
    model.load_state_dict(torch.load(CKPT_DIR / 'best_model.pth', map_location=device))
    model.eval()
    print("Model loaded from checkpoint.")

    with rasterio.open(STACK_PATH) as src:
        profile   = src.profile.copy()
        H, W      = src.height, src.width
        print(f"Input raster: {H} × {W} pixels")

        # Accumulators for overlapping tile averaging
        pred_sum   = np.zeros((H, W), dtype=np.float32)
        pred_count = np.zeros((H, W), dtype=np.float32)

        rows = range(0, H, STRIDE)
        cols = range(0, W, STRIDE)
        total = len(list(rows)) * len(list(cols))

        with tqdm(total=total, desc='Running inference') as pbar:
            for r in range(0, H, STRIDE):
                for c in range(0, W, STRIDE):
                    # Read tile directly from file (saves RAM vs loading full image)
                    r_end = min(r + TILE_SIZE, H)
                    c_end = min(c + TILE_SIZE, W)
                    window = rasterio.windows.Window(c, r, c_end - c, r_end - r)
                    patch  = src.read(window=window).astype(np.float32) / REFLECTANCE_SCALE

                    # Pad to TILE_SIZE × TILE_SIZE if we're at the edge
                    ph, pw = patch.shape[1], patch.shape[2]
                    if ph < TILE_SIZE or pw < TILE_SIZE:
                        padded = np.zeros((IN_CHANNELS, TILE_SIZE, TILE_SIZE), dtype=np.float32)
                        padded[:, :ph, :pw] = patch
                        patch = padded

                    # Inference
                    with torch.no_grad():
                        tensor = torch.from_numpy(patch).unsqueeze(0).to(device)  # (1,4,256,256)
                        logit  = model(tensor)
                        prob   = torch.sigmoid(logit).squeeze().cpu().numpy()       # (256,256)

                    # Only accumulate the valid (non-padded) region
                    pred_sum[r:r_end, c:c_end]   += prob[:r_end-r, :c_end-c]
                    pred_count[r:r_end, c:c_end] += 1.0
                    pbar.update(1)

    # Average overlapping predictions
    pred_avg    = pred_sum / np.maximum(pred_count, 1e-6)
    binary_mask = (pred_avg > THRESHOLD).astype(np.uint8)

    # ── Topology Trick: Morphological Closing ──
    # Connects disconnected 1-3 pixel gaps along a straight road segment
    import cv2
    print("Applying morphological closing to connect dotted road fragments...")
    kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (5, 5))
    binary_mask = cv2.morphologyEx(binary_mask, cv2.MORPH_CLOSE, kernel)

    print(f"Road pixels predicted: {binary_mask.sum():,} / {H*W:,} "
          f"({binary_mask.sum()/(H*W)*100:.2f}%)")

    # Write georeferenced output — CRITICAL: preserve original transform and CRS
    profile.update({
        'dtype':   'uint8',
        'count':   1,
        'nodata':  255,
        'compress': 'lzw'   # reduces file size significantly
    })

    with rasterio.open(PRED_MASK_PATH, 'w', **profile) as dst:
        dst.write(binary_mask, 1)

    print(f"Predicted mask saved to: {PRED_MASK_PATH}")
    return PRED_MASK_PATH

run_inference()

from google.colab import runtime
runtime.unassign()

"""## Cell 12 — Visualise Prediction (Quick Check)"""

import matplotlib.pyplot as plt
import rasterio
from rasterio.plot import show

fig, axes = plt.subplots(1, 2, figsize=(16, 8))

# Show RGB composite of the input stack (bands 3,2,1 = Red,Green,Blue)
with rasterio.open(STACK_PATH) as src:
    rgb = src.read([3, 2, 1])   # Red=B04, Green=B03, Blue=B02
    rgb = (rgb / 3000.0).clip(0, 1)   # stretch for display
    show(rgb, ax=axes[0], title='RGB Composite (B04-B03-B02)')

# Show predicted road mask
with rasterio.open(PRED_MASK_PATH) as src:
    show(src, ax=axes[1], title='Predicted Road Mask (white = road)', cmap='gray')

plt.tight_layout()
plt.savefig(OUTPUT_DIR / 'prediction_preview.png', dpi=150)
plt.show()
print("Preview saved.")

"""## Cell 13 — Vectorise Predicted Mask → Shapefile
Converts `segmentation_mask_predicted.tif` to `predicted_roads.shp` — the polyline Shapefile consumed by Stage 4.

Attributes produced: `road_id` (int), `length_m` (float). Stage 4 will add `condition` and `confidence`. Stage 5 will add `connected_component_id`.
"""

import rasterio
import rasterio.features
import geopandas as gpd
from shapely.geometry import shape, MultiPolygon
from shapely.ops import unary_union
import warnings
warnings.filterwarnings('ignore')

def vectorise_mask():
    print("Reading predicted mask...")
    with rasterio.open(PRED_MASK_PATH) as src:
        binary = src.read(1)           # (H, W) uint8
        transform = src.transform
        crs = src.crs

    print(f"CRS: {crs}  |  Road pixels: {binary.sum():,}")

    # ── Step 1: Polygonize ─────────────────────────────────────────────────
    print("Polygonizing...")
    shapes = list(rasterio.features.shapes(binary, mask=(binary == 1), transform=transform))
    print(f"Raw polygons: {len(shapes)}")

    polygons = [shape(geom) for geom, val in shapes if val == 1]

    # ── Step 2: Filter tiny noise polygons (< 200 m² = ~2 pixels at 10m) ──
    min_area = 200  # square metres
    polygons = [p for p in polygons if p.area >= min_area]
    print(f"After noise filter (≥{min_area} m²): {len(polygons)} polygons")

    if not polygons:
        print("WARNING: No polygons remain after filtering. Check threshold and prediction quality.")
        return None

    # ── Step 3: Extract boundaries (polygon → linestring) ──────────────────
    lines = []
    for poly in polygons:
        boundary = poly.boundary
        # Simplify to remove pixel staircase artefacts (10m tolerance = 1 pixel)
        simplified = boundary.simplify(tolerance=10.0, preserve_topology=True)
        if simplified.is_empty:
            continue
        # Handle MultiLineString boundaries
        if simplified.geom_type == 'MultiLineString':
            lines.extend(list(simplified.geoms))
        else:
            lines.append(simplified)

    # ── Step 4: Filter very short segments (< 20m) ────────────────────────
    min_length = 20.0  # metres
    lines = [l for l in lines if l.length >= min_length]
    print(f"Linestrings after length filter (≥{min_length}m): {len(lines)}")

    # ── Step 5: Build GeoDataFrame and save ───────────────────────────────
    gdf = gpd.GeoDataFrame({
        'road_id':  list(range(len(lines))),
        'length_m': [round(l.length, 2) for l in lines],
        'geometry': lines
    }, crs=crs)   # EPSG:32642 — required for Stage 4 spatial joins

    gdf.to_file(PRED_SHP_PATH)
    print(f"\nShapefile saved: {PRED_SHP_PATH}")
    print(f"Total road segments: {len(gdf)}")
    print(f"Total road length: {gdf['length_m'].sum()/1000:.2f} km")
    return gdf

gdf = vectorise_mask()
if gdf is not None:
    gdf.head()

"""## Cell 13b — Test on a New Unseen Image
Use this cell to run your trained model on a brand new `.tif` file without altering your main pipeline outputs.
"""

# 1. Install missing packages (required for a fresh session)
!pip install -q rasterio segmentation-models-pytorch

# 2. Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# 3. Imports
import rasterio
import torch
import numpy as np
from tqdm.notebook import tqdm
from pathlib import Path
import segmentation_models_pytorch as smp

# 4. Configurations & Paths
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
DRIVE_ROOT   = Path('/content/drive/MyDrive/FYP')
RAW_DIR      = DRIVE_ROOT / 'data' / 'raw'
OUTPUT_DIR   = DRIVE_ROOT / 'outputs'
CKPT_DIR     = OUTPUT_DIR / 'checkpoints'

TILE_SIZE = 256
STRIDE = 128
REFLECTANCE_SCALE = 10000.0
IN_CHANNELS = 4
THRESHOLD = 0.5

# 5. Define Model Architecture
model = smp.DeepLabV3Plus(
    encoder_name    = 'se_resnext101_32x4d',
    encoder_weights = 'imagenet',
    in_channels     = IN_CHANNELS,
    classes         = 1,
    activation      = None,
).to(device)

# --- 6. SET YOUR NEW FILE NAME HERE ---
NEW_TIF_NAME = 'sindh_stack_clipped1.tif'  # Make sure it is uploaded to My Drive/FYP/data/raw/
TRUE_MASK_NAME = 'sindh_stack_clipped1_road_mask.tif' # Ground truth mask
# --------------------------------------

NEW_STACK_PATH = RAW_DIR / NEW_TIF_NAME
TRUE_MASK_PATH = RAW_DIR / TRUE_MASK_NAME
NEW_PRED_PATH  = OUTPUT_DIR / f"pred_{NEW_TIF_NAME}"

def run_custom_inference(input_path, output_path):
    if not input_path.exists():
        print(f"Error: Could not find {input_path}. Did you upload it to the 'raw' folder?")
        return

    print(f"Loading model weights for {input_path.name}...")
    model.load_state_dict(torch.load(CKPT_DIR / 'best_model.pth', map_location=device))
    model.eval()

    with rasterio.open(input_path) as src:
        profile = src.profile.copy()
        H, W = src.height, src.width
        print(f"Input raster: {H} × {W} pixels")

        pred_sum = np.zeros((H, W), dtype=np.float32)
        pred_count = np.zeros((H, W), dtype=np.float32)

        # Process the image in overlapping patches
        total_tiles = len(range(0, H, STRIDE)) * len(range(0, W, STRIDE))
        with tqdm(total=total_tiles, desc='Running custom inference') as pbar:
            for r in range(0, H, STRIDE):
                for c in range(0, W, STRIDE):
                    r_end = min(r + TILE_SIZE, H)
                    c_end = min(c + TILE_SIZE, W)
                    window = rasterio.windows.Window(c, r, c_end - c, r_end - r)
                    patch = src.read(window=window).astype(np.float32) / REFLECTANCE_SCALE

                    # Pad edges if necessary
                    ph, pw = patch.shape[1], patch.shape[2]
                    if ph < TILE_SIZE or pw < TILE_SIZE:
                        padded = np.zeros((IN_CHANNELS, TILE_SIZE, TILE_SIZE), dtype=np.float32)
                        padded[:, :ph, :pw] = patch
                        patch = padded

                    # Inference
                    with torch.no_grad():
                        tensor = torch.from_numpy(patch).unsqueeze(0).to(device)
                        logit = model(tensor)
                        prob = torch.sigmoid(logit).squeeze().cpu().numpy()

                    # Accumulate predictions
                    pred_sum[r:r_end, c:c_end] += prob[:r_end-r, :c_end-c]
                    pred_count[r:r_end, c:c_end] += 1.0
                    pbar.update(1)

        # Average overlapping tiles
        pred_avg = pred_sum / np.maximum(pred_count, 1e-6)
        binary_mask = (pred_avg > THRESHOLD).astype(np.uint8)

    # Save output
    profile.update({'dtype': 'uint8', 'count': 1, 'nodata': 255, 'compress': 'lzw'})
    with rasterio.open(output_path, 'w', **profile) as dst:
        dst.write(binary_mask, 1)

    print(f"\nSuccess! Predicted mask saved to: {output_path}")

# Run the function
run_custom_inference(NEW_STACK_PATH, NEW_PRED_PATH)

# --- 7. EVALUATE ACCURACY AGAINST GROUND TRUTH ---
if TRUE_MASK_PATH.exists() and NEW_PRED_PATH.exists():
    print(f"\nEvaluating predicted mask against {TRUE_MASK_NAME}...")
    with rasterio.open(NEW_PRED_PATH) as pred_src:
        pred_mask = pred_src.read(1)
    with rasterio.open(TRUE_MASK_PATH) as true_src:
        true_mask = true_src.read(1)

    # Convert masks to boolean maps to handle variations in label values (e.g., 255 vs 1)
    pred_bool = (pred_mask == 1)
    true_bool = (true_mask > 0)

    intersection = np.logical_and(pred_bool, true_bool).sum()
    union = np.logical_or(pred_bool, true_bool).sum()

    iou = intersection / union if union > 0 else 0
    precision = intersection / pred_bool.sum() if pred_bool.sum() > 0 else 0
    recall = intersection / true_bool.sum() if true_bool.sum() > 0 else 0
    f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

    print(f"\n--- Evaluation Metrics ---")
    print(f"Intersection over Union (IoU): {iou:.4f}")
    print(f"Precision:                     {precision:.4f}")
    print(f"Recall (Sensitivity):          {recall:.4f}")
    print(f"F1-Score:                      {f1_score:.4f}")
else:
    print(f"\nCould not find true mask at {TRUE_MASK_PATH} to run evaluation.")

import matplotlib.pyplot as plt
import rasterio
from rasterio.plot import show

# Ensure the file exists before trying to plot
if NEW_PRED_PATH.exists() and NEW_STACK_PATH.exists():
    fig, axes = plt.subplots(1, 2, figsize=(16, 8))

    # Show RGB composite of the input stack (bands 3,2,1 = Red,Green,Blue)
    with rasterio.open(NEW_STACK_PATH) as src:
        rgb = src.read([3, 2, 1])   # Red=B04, Green=B03, Blue=B02
        rgb = (rgb / 3000.0).clip(0, 1)   # stretch for display
        show(rgb, ax=axes[0], title=f'RGB Composite ({NEW_STACK_PATH.name})')

    # Show predicted road mask
    with rasterio.open(NEW_PRED_PATH) as src:
        show(src, ax=axes[1], title=f'Predicted Road Mask ({NEW_PRED_PATH.name})', cmap='gray')

    plt.tight_layout()
    plt.show()
else:
    print(f"Make sure you have run the inference cell above successfully. Could not find {NEW_PRED_PATH.name}")

"""## Cell 14 — Session Survival Check
Colab sessions disconnect after ~90 minutes of inactivity or 12 hours total.
Run this cell periodically or after reconnecting to confirm your Drive outputs are intact.
"""

files_to_check = [
    CKPT_DIR / 'best_model.pth',
    OUTPUT_DIR / 'training_metrics.json',
    OUTPUT_DIR / 'training_curves.png',
    PRED_MASK_PATH,
    PRED_SHP_PATH,
]

print("Output file status:")
for f in files_to_check:
    size = f"{f.stat().st_size / 1e6:.1f} MB" if f.exists() else "MISSING"
    status = "✓" if f.exists() else "✗"
    print(f"  {status} {f.name:<45} {size}")

print(f"\nTile count — images: {len(list((TILES_DIR/'images').glob('*.npy')))}  "
      f"masks: {len(list((TILES_DIR/'masks').glob('*.npy')))}")

from google.colab import runtime
runtime.unassign()

"""---
## Handoff to Stage 4

Stage 3 is complete when the following files exist in your Google Drive:

| File | Used by Stage 4 as |
|------|--------------------|
| `outputs/segmentation_mask_predicted.tif` | Source for 64×64 patch extraction along road centrelines |
| `outputs/predicted_roads.shp` (+ `.shx`, `.dbf`, `.prj`) | Road segments to classify as Good / Damaged / Unpaved |

Both files preserve **EPSG:32642** CRS and the original geotransform of `sindh_stack.tif`.
Stage 4's EfficientNet classifier will add `condition` and `confidence` columns to the Shapefile.
"""